/**
 * Generate CALL-SHEET.md — every outstanding verification item, in one place.
 *
 * These items live scattered across the data files, next to the facts they
 * qualify, which is right: an `outstanding` array belongs beside the record it
 * doubts. But you don't make phone calls by grepping JSON. This pulls them all
 * into one ordered list you can work down with a phone in your hand.
 *
 * Generated, never hand-edited — a hand-kept version would drift from the data
 * within a week and then quietly lie about what's been done.
 *
 * Ordered by consequence, not by file:
 *   1. Emergency — a stale vet number is the only error here that hurts a dog
 *   2. Towns     — wrong dates cost a wasted trip or a fine
 *   3. Places    — the summer answers
 *   4. Parks     — nice to have, low stakes
 *   5. Lodging   — the four numbers that unlock the affiliate
 *
 * Run: npm run calls
 */
import { readFileSync, writeFileSync } from "node:fs";

const read = (p) => JSON.parse(readFileSync(p, "utf8"));

const towns = read("src/data/towns.json");
const parks = read("src/data/parks.json");
const places = read("src/data/places.json");
const emergency = read("src/data/emergency.json");
const lodging = read("src/data/lodging.json");
const community = (() => {
  try {
    return read("src/data/community-parks.json");
  } catch {
    return [];
  }
})();
const statePark = (() => {
  try {
    return read("src/data/state-parks.json");
  } catch {
    return [];
  }
})();

const done = (r) => r.verifiedDate && r.verifiedSource;
const lines = [];
let open = 0;

const section = (heading, blurb) => {
  lines.push(``, `## ${heading}`, ``);
  if (blurb) lines.push(blurb, ``);
};

const entry = (name, phone, items) => {
  if (!items?.length) return;
  open += items.length;
  lines.push(`### ${name}${phone ? ` — ${phone}` : ""}`, ``);
  for (const i of items) lines.push(`- [ ] ${i}`);
  lines.push(``);
};

lines.push(
  `# Call sheet`,
  ``,
  `> Generated by \`npm run calls\` from the data files. Do not edit by hand —`,
  `> tick items off by filling in \`verifiedDate\` and \`verifiedSource\` on the`,
  `> record itself, then re-run. An item disappears from this list when the`,
  `> record it belongs to is verified.`,
  ``,
  `Ordered by consequence. The emergency numbers are first because they are the`,
  `only ones on this site where being wrong hurts a dog rather than costing a`,
  `trip.`,
);

/* 1 — Emergency */
section(
  "1. Emergency contacts",
  "**Highest priority.** Coastal practices move their hours seasonally and a\nnumber that rings nowhere at 11pm is worse than no number at all.",
);
entry("Emergency data (src/data/emergency.json)", null, emergency.outstanding);
for (const v of emergency.vets.filter((v) => !done(v))) {
  entry(v.name, v.phone ?? "number unknown", [
    `Confirm the number rings the right place.`,
    `Confirm hours: currently recorded as "${v.hours}".`,
    v.phone ? null : `Find the phone number.`,
  ].filter(Boolean));
}

/* 2 — Towns */
section("2. Beach towns", "Wrong dates here cost someone a three-hour drive or a fine.");
for (const t of towns.filter((t) => !done(t))) {
  entry(t.name, t.callTo?.phone, t.outstanding);
}

/* 3 — Places */
section("3. Summer places", "The answers on /dogs/summer/ — the pages with no competitor.");
for (const p of places.filter((p) => !done(p))) {
  entry(p.name, null, [
    `Confirm dogs are permitted as described: "${p.headline}"`,
    `Confirm the fee note: "${p.feeNote}"`,
  ]);
}

/* 4 — State parks */
if (statePark.length) {
  section("4. State parks", "Section two. Lower stakes — mostly hours, fees and facilities.");
  for (const p of statePark.filter((p) => !done(p))) {
    entry(p.name, p.phone, p.outstanding);
  }
}

/* 4b — Community parks */
if (community.length) {
  section("4b. Community parks", "Restrooms first — it is the field people actually ask about and the one\nmost often missing here.");
  for (const p of community.filter((p) => !done(p))) {
    entry(p.name, p.phone, p.outstanding);
  }
}

/* 5 — Dog parks */
section(
  "5. Dog parks",
  "Google's posted hours usually belong to the parent park rather than the dog\nrun inside it, which is why so many of these are unconfirmed.",
);
for (const p of parks.filter((p) => !done(p))) {
  entry(p.name, null, p.outstanding);
}

/* 6 — Lodging */
const props = lodging.filter((l) => typeof l.name === "string" && l.petFee?.amount === null);
section(
  "6. Pet fees",
  "Ask all four on every call — fee **total**, weight limit, dog count, unattended\npolicy — then the bonus question: *what do guests ask you most often before\nthey book with a dog?* That last one is free demand research.",
);
for (const l of props) {
  entry(`${l.name} — ${l.town}`, l.phone, [
    "Pet fee, total. Per night or per stay?",
    "Weight limit?",
    "How many dogs?",
    "Can the dog be left in the room unattended?",
    "What do guests ask you most often before booking with a dog?",
  ]);
}

lines.push(
  ``,
  `---`,
  ``,
  `**${open} open items.** Every one of them is a fact this site cannot publish`,
  `until someone picks up a phone. That is the moat, not overhead.`,
  ``,
);

writeFileSync("CALL-SHEET.md", lines.join("\n"));
console.log(`  ✓ CALL-SHEET.md — ${open} open items`);
